### ISSUE TITLE
Limit port access to restricted number of hosts

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#108]
Currently it is only possible to open port to the world. E.g 
```
ports:
  - type: TCP
    number: 80
```
open port 80 to everyone. It would be nice to restrict the access to one or a group of hosts. Allow only hosts from 129.70.160.0/24 access masters port 80 could be configured as follows.
```
ports:
  - type: TCP
    number: 80
    cidr: 129.70.160.0/24
```
