### ISSUE TITLE
Zabbix breaks configuration

### ISSUE THREAD

**Issue by a1an77** [BiBiServ/bibigrid#141]
Adding the zabbix sections to my config file seems to break the configuration. I'm getting an error when trying out the -ch option:

    Ok : NFS shares set: /vol/spool /vol/silva /vol/silvadata 
    Ok : Additional open ports set: 0.0.0.0/0:80 (TCP) 
    ERROR: Aborting operation. No instances started/terminated. [StartUp:157]

The content I added to the working file is:

    # Monitoring
    zabbix: yes
    zabbixConf:
        db_password: xxxx
        servername: myserver
        admin_password: yyyy

BiBiGrid 2.0.5

**Comment by jkrue** [comment]
There is a typo in config schema documentation, The `zabbixConf ` property `servername` must be `server_name`.
Changing your configuration snipet  ...
```
# Monitoring
zabbix: yes
zabbixConf:
    db_password: xxxx
    server_name: myserver
    admin_password: yyyy
```
works.
