### ISSUE TITLE
Local DNS lookup

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#170]
We should add the possibility of local dns lookup (host entries in `/etc/hosts`  in the case a DNS  is not available or malformed. Since we use ansible to configure our master  and all worker nodes this is quite easy - all necessary informations are available. The following task should do the work 
```
- name: Update the /etc/hosts file with node name
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ item.ip }}\t{{ item.hostname }}"
    line: "{{ item.ip }}\t{{ item.hostname }}"
    state: present
    backup: yes
  with_items: 
    - "{{ master }}"
    - "{{ workers }}"
```
