### ISSUE TITLE
Update & upgrade entire system 

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#193]
The current playbook does *not* trigger an update/upgrade of the entire system. We extend the apt task as follows:
```
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
```
