### ISSUE TITLE
Add application credentials to the cluster

### ISSUE THREAD

**Issue by tdilger** [BiBiServ/bibigrid#330]
According to #329 (2), OS application credentials should be created and placed inside /etc/openstack/clouds.yml (read-only for slurm user) as follows: 
```
clouds:
  bibigrid_cluster:
    auth_url: <auth_url>
    auth_type: v3applicationcredential
    application_credential_id: <id>
    application_credential_secret: <secret>

Then the openstack CLI client can be used like this

openstack --os-cloud bibigrid_cluster <command>**
```
With Openstack4J we can solve this via [OSClientV3 Identity Service](https://openstack4j.github.io/learn/identity/identity-v3/) by using os.identity().create(...) and use them accordingly.
