### ISSUE TITLE
Add ephemeral disk value to instances.yml

### ISSUE THREAD

**Issue by patricS4** [BiBiServ/bibigrid#333]
In order to use ephemeral data inside the Slurm template (`TmpDisk`), the `ephemeral_disk` variable should be [generated in the `instances.yml` when creating the cluster](https://github.com/BiBiServ/bibigrid/blob/9c459ab78513ca36b9b6a6338f11775e706dfa95/bibigrid-core/src/main/java/de/unibi/cebitec/bibigrid/core/model/AnsibleConfig.java#L453).

`instances.yml` example:
```
workers:
- cores: 14
   ephemeral_disk: 1000
   ephemerals:
   - dev/vdb
   hostname: bibigrid-worker-4-9-***
   ip: ***.***.*.***
   Memory: 131072
   status: ACTIVE
- cores: 1
  ephemeral_disk: 0
  ephemerals: []
  hostname: bibigrid-worker-4-8-***
  ip: ***.***.*.***
  memory: 2048
  status: ACTIVE
```

**Comment by jkrue** [comment]
If more than one ephemeral disc is present, what should be the value for an `ephemeral_disk`, then?   
-> `ephemerals` describe a  list of disks.
(This can't happen in  Openstack setups as I know,  but in general, this is possible).

**Comment by jkrue** [comment]
What about the following solution?
```
ephemerals:
  /dev/vdb:
    size: 50
    mountpoint: /vol 
```
