### ISSUE TITLE
Hybrid Cloud

### ISSUE THREAD

**Issue by XaverStiensmeier** [BiBiServ/bibigrid#371]
Implement Hybrid Cloud using Wireguard.

- [x] Automatically register the wireguard service so that systemd-networkd can start it up if needed values are given in the common configuration
- [x] #376
- [x] #372
- [x] #375
- [x] #373
- [x] #374
- [x] #378
- [x] #377
- [x] #379
- [x] #381

**Comment by XaverStiensmeier** [comment]
Format of vpnwkrs in `ansible_host.yml`:

```
workers:
  children:
    vpnwkrs:
      hosts:
        bibigrid-vpnwkr-3edh7whtij6mt19:
            ansible_connection: ssh
            ansible_python_interpreter: /usr/bin/python3
            ansible_user: ubuntu
            ansible_host: ip
```
Format of necessary common configuration:
```
wireguard:
  peers:
  - name: name
    private_key:
    public_key:
    ip:
    subnet:
  - ...
```
