### ISSUE TITLE
Support different flavors for slave instances

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#38]
Supporting different flavors for slave instances cloud be useful, when using BiBiGrid for a worfklow that  have very different resource requirements for its single tasks. Not sure how to implement this in a useful manner but it is interesting idea and challenge for the future ...

**Comment by AstrorEnales** [comment]
Multiple slave configurations can now be requested in the new yaml config files. For example:
```
slaveInstances:
  - type: flavor1
    count: 2
    image: ubuntu-1604
  - type: flavor2
    count: 1
    image: ubuntu-1604
```
