### ISSUE TITLE
Ephemeral disk not found

### ISSUE THREAD

**Issue by ChiaraVanni** [BiBiServ/bibigrid#416]
Hi,

I recently create a cluster with bibigrid and everything ran smoothly, only I don't see any "/vol/scratch" or ephemeral disk. I didn't explicitly specify this in the bibigrid.yml file (here attached). Is there a way to set the local ephemeral disk with the cluster up and running? If not, where should I specify that I want an ephemeral disk in the bibigrid.yml config. file?
Many thanks for the help!

Chiara
[bibigrid.txt](https://github.com/BiBiServ/bibigrid/files/11665447/bibigrid.txt)

**Comment by XaverStiensmeier** [comment]
Hi,

good catch! Thanks to your issue I noticed that we haven't documented ephemeral yet. I will catch up on that soon.

As a first short answer: Maybe your ephemerals got detected correctly, but you are looking at the wrong spot? On your master ephemeral is mounted to `/vol/` and on your workers to `/vol/scratch`. We agreed to copy the behavior of the old BiBiGrid at this point. However, I am not quite sure why the old bibigrid used two different paths and need to check with Jan.

If that's not it, we need to dig a little deeper:

1. In the `bibigrid/resources/group_vars` files what's stored under 
```yaml
flavor:
    ephemeral: ?
```

If this is 0 than something is wrong with the assignment. In that case a manual fix would be to store the available ephemeral there (should be 1950000). Otherwise something is wrong with the Ansible execution.

2. If this wasn't 0 then please check whether `TASK [bibigrid : Create /vol bind mount from /mnt ephemeral]` has been skipped. You can check this in the logfile or - in every case - run Ansible again on your remote machine: when logged into your remote machine, execute `bibiplay -l master`.

Xaver

**Comment by ChiaraVanni** [comment]
Hi,
in the `bibigrid/resources/group_vars` files I have the ephemerals

```
cloud_identifier: openstack
flavor:
  disk: 50
  ephemeral: 2000
  name: de.NBI highmem xlarge
  ram: 491520
  vcpus: 28
gateway_ip: 192.168.0.235
image: Ubuntu 22.04 LTS (2023-02-14)
name: bibigrid-worker0-cv6j7rvcuvf1ifr-[0-4]
network: 74074d13-4d59-469a-8d3c-978097938952
regexp: bibigrid-worker0-cv6j7rvcuvf1ifr-\d+
```

When running `bibiplay -l master` I get this:

```
TASK [bibigrid : Create /vol bind mount from /mnt ephemeral] *********************************************************************************************************************************************************
ok: [localhost]

TASK [bibigrid : Mount disks] ****************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [bibigrid : Mount ephemeral] ************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [bibigrid : Set 0777 rights for ephemeral mount] ****************************************************************************************************************************************************************
skipping: [localhost]
```


My `ansible_hosts` file looks like this:

```
vpn:
  children:
    master:
      hosts:
        localhost:
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: ubuntu
          ip: localhost
    vpngtw:
      hosts: {}
  hosts: {}
workers:
  children:
    bibigrid_worker0_cv6j7rvcuvf1ifr_0_4:
      hosts:
        bibigrid-worker0-cv6j7rvcuvf1ifr-[0:4]:
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: ubuntu
  hosts: {}
```

Thanks!

Chiara
